version: '3.8'

services:
  chatboot-rag:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_MODEL=gemma2:2b
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
